#ifndef __TILEMAP_H__
#define __TILEMAP_H__
#include <common.h>
#include <texture.h>



enum TILEMAP_TEX_IMG{
	TILEMAP_TEX_IMG_BLOCK_CLIFF_LEFT=0x0,
	TILEMAP_TEX_IMG_BLOCK_CLIFF_LEFT_2=0x1,
	TILEMAP_TEX_IMG_BLOCK_CLIFF_RIGH=0x2,
	TILEMAP_TEX_IMG_BLOCK_CLIFF_RIGHT_2=0x3,
	TILEMAP_TEX_IMG_BLOCK_EDGE_LEFT=0x4,
	TILEMAP_TEX_IMG_BLOCK_FULL=0x5,
	TILEMAP_TEX_IMG_BLOCK_HALF=0x6,
	TILEMAP_TEX_IMG_BLOCK_HALF_LEFT=0x7,
	TILEMAP_TEX_IMG_BLOCK_HALF_MIDDLE=0x8,
	TILEMAP_TEX_IMG_BLOCK_HALF_RIGHT=0x9,
	TILEMAP_TEX_IMG_BLOCK_HILL_LEFT=0xa,
	TILEMAP_TEX_IMG_BLOCK_HILL_LEFT_2=0xb,
	TILEMAP_TEX_IMG_BLOCK_HILL_RIGHT=0xc,
	TILEMAP_TEX_IMG_BLOCK_HILL_RIGHT_2=0xd,
	TILEMAP_TEX_IMG_BLOCK_LEFT=0xe,
	TILEMAP_TEX_IMG_BLOCK_MIDDLE=0xf,
	TILEMAP_TEX_IMG_BLOCK_RIGHT_EDGE=0x10,
	TILEMAP_TEX_IMG_BLOCK_ROUND=0x11,
	TILEMAP_TEX_IMG_BLOCK_TOP=0x12,
	TILEMAP_TEX_IMG_FLOACK_RIGHT=0x13,
	TILEMAP_TEX_IMG_PLAYER_CLIMB_1=0x14,
	TILEMAP_TEX_IMG_PLAYER_CLIMB_2=0x15,
	TILEMAP_TEX_IMG_PLAYER_DAMAGE=0x16,
	TILEMAP_TEX_IMG_PLAYER_DUCK=0x17,
	TILEMAP_TEX_IMG_PLAYER_JUMP=0x18,
	TILEMAP_TEX_IMG_PLAYER_STAND=0x19,
	TILEMAP_TEX_IMG_PLAYER_STAND_FRONT=0x1a,
	TILEMAP_TEX_IMG_PLAYER_SWIM_1=0x1b,
	TILEMAP_TEX_IMG_PLAYER_SWIM_2=0x1c,
	TILEMAP_TEX_IMG_PLAYER_WALK_1=0x1d,
	TILEMAP_TEX_IMG_PLAYER_WALK_2=0x1e,
	TILEMAP_TEX_IMG_SIDE_PAD=0x1f,
	TILEMAP_TEX_IMG_SIDE_PAD_EDGE=0x20,
};



extern const uint8_t TILEMAP_TEX_DATA[];



extern const RawTexture TILEMAP_TEX;



extern const TextureMapData TILEMAP_TEX_MAP_DATA[];



#endif
